/**
 * Suspension.js — Spring & Damper model per corner with bump steer.
 */
export class Suspension {
  constructor(config) {
    this.restLength     = config.restLength || 0.30;
    this.springRate     = config.springRate || 30000;
    this.damperBump     = config.damperBump || 3000;
    this.damperRebound  = config.damperRebound || 4000;
    this.bumpSteerCoeff = config.bumpSteerCoeff || 0.002;
  }

  /**
   * Compute normal force (Fz) generated by suspension spring and damper.
   * @param {number} currentLength Distance from chassis mount to ground along suspension ray
   * @param {number} compressionVel Rate of change of length (m/s), >0 means compressing
   * @returns {number} Spring force + Damping force (N), clamped >= 0
   */
  computeForce(currentLength, compressionVel) {
    // Compression amount (meters)
    const compression = this.restLength - currentLength;

    if (compression <= 0) {
      return 0; // Unloaded / wheel off ground
    }

    // Spring force (Hooke's Law)
    const springForce = compression * this.springRate;

    // Damping force (separate bump vs rebound rates)
    const damperRate = compressionVel >= 0 ? this.damperBump : this.damperRebound;
    const damperForce = compressionVel * damperRate;

    // Total normal force pushing car up & tyre down
    return Math.max(0, springForce + damperForce);
  }

  /**
   * Compute bump steer angle offset (radians) based on suspension travel.
   * @param {number} currentLength Current suspension strut length
   * @returns {number} Steering angle offset in radians
   */
  getBumpSteerAngle(currentLength) {
    const compression = this.restLength - currentLength;
    if (compression <= 0) return 0;
    return compression * this.bumpSteerCoeff;
  }
}
